In [1]:
import os

In [5]:
Dir = r"C:\Users\Rishabh\Downloads\label_192\label_192"
ground_truths = os.path.join(Dir, 'ground truths')
images = os.path.join(Dir, 'images')

In [6]:
images

'C:\\Users\\Rishabh\\Downloads\\label_192\\label_192\\images'

In [7]:
ground_truths

'C:\\Users\\Rishabh\\Downloads\\label_192\\label_192\\ground truths'

In [10]:
len(os.listdir(images))

192

In [11]:
len(os.listdir(ground_truths))

192

In [54]:
import nibabel as nib
import numpy as np

# Load the NIfTI file
for index in range(len(os.listdir(images))):
    nii_segementation = nib.load(os.path.join(ground_truths, os.listdir(images)[index]))
    nii_image = nib.load(os.path.join(images, os.listdir(images)[index]))
    
    # Get the image data as a NumPy array
    image_data = nii_image.get_fdata()
    segementation_data = nii_segementation.get_fdata()
    # print(image_data.shape,'  ',segementation_data.shape)
    print(np.unique(segementation_data))
    # if image_data.shape != segementation_data.shape:
    #     print("wrong")
    


[0. 2. 3.]
[0. 2. 5.]
[0. 2. 3. 4.]
[0. 2. 3.]
[0. 1. 2. 5.]
[0. 2. 3.]
[0. 2. 4. 5.]
[0. 2.]
[0. 2. 3.]
[0. 2. 3. 4. 5.]
[0. 1.]
[0. 2. 4. 5.]
[0. 3. 4.]
[0. 2.]
[0. 2. 4. 5.]
[0. 2. 4. 5.]
[0. 2. 4.]
[0. 2. 3.]
[0. 2. 3. 4. 5.]
[0. 2. 3.]
[0. 2. 3. 4.]
[0. 3.]
[0. 2. 4.]
[0. 5.]
[0. 2.]
[0. 2. 3. 4.]
[0. 2. 3. 4.]
[0. 2. 4. 5.]
[0. 1.]
[0. 4. 5.]
[0. 1. 4.]
[0. 5.]
[0. 1. 4.]
[0. 1. 4.]
[0. 1. 5.]
[0. 2. 3. 4. 5.]
[0. 2. 3.]
[0. 2. 4.]
[0. 1. 2. 5.]
[0. 2. 3. 4.]
[0. 3.]
[0. 5.]
[0. 2. 3. 4.]
[0. 1. 4. 5.]
[0. 2. 3.]
[0. 1.]
[0. 2. 3. 5.]
[0. 2. 3. 4.]
[0. 2. 4.]
[0. 4.]
[0. 3. 4. 5.]
[0. 2. 3.]
[0. 2. 4. 5.]
[0. 2. 3.]
[0. 2. 3.]
[0. 3. 4.]
[0. 2. 3. 4.]
[0. 2. 5.]
[0. 2. 3. 4. 5.]
[0. 2. 3. 4. 5.]
[0. 2. 4. 5.]
[0. 2.]
[0. 1. 2. 3. 4.]
[0. 1.]
[0. 2. 3. 4.]
[0. 1.]
[0. 2. 3. 4.]
[0. 2. 4. 5.]
[0. 3. 4. 5.]
[0. 3. 4.]
[0. 2. 3.]
[0. 2. 3. 4.]
[0. 3. 4. 5.]
[0. 1.]
[0. 1.]
[0. 2. 3.]
[0. 2. 4.]
[0. 4.]
[0. 2.]
[0. 3.]
[0. 2. 3. 4.]
[0. 2. 3.]
[0. 4. 5.]
[0. 3. 4. 5.]
[0. 3. 4. 5.]
[0

In [35]:
index = 10
nii_segementation = nib.load(os.path.join(ground_truths, os.listdir(images)[index]))
nii_image = nib.load(os.path.join(images, os.listdir(images)[index]))

# Get the image data as a NumPy array
image_data = nii_image.get_fdata()
segementation_data = nii_segementation.get_fdata()

In [36]:
image_data.shape

(512, 512, 32)

In [37]:
segementation_data.shape

(512, 512, 32)

In [46]:
from PIL import Image
for slice_index in range(segementation_data.shape[2]): 
    print(slice_index, '   ', np.unique(segementation_data[:,:,slice_index]))
    # image_slice = Image.fromarray(image_data[:,:,slice_index])
    # segementation_slice = Image.fromarray(segementation_data[:,:,slice_index])

0     [0.]
1     [0.]
2     [0.]
3     [0.]
4     [0.]
5     [0.]
6     [0. 1.]
7     [0. 1.]
8     [0. 1.]
9     [0. 1.]
10     [0. 1.]
11     [0. 1.]
12     [0.]
13     [0.]
14     [0.]
15     [0.]
16     [0.]
17     [0.]
18     [0.]
19     [0.]
20     [0.]
21     [0.]
22     [0.]
23     [0.]
24     [0.]
25     [0.]
26     [0.]
27     [0.]
28     [0.]
29     [0.]
30     [0.]
31     [0.]


In [44]:
image_slice.show()

In [52]:
segementation_slice.show()

In [51]:
slice_index = 7
image_slice = Image.fromarray(image_data[:,:,slice_index])
segementation_slice = Image.fromarray(segementation_data[:,:,slice_index])

In [ ]:
from torch.utils.data import Dataset, DataLoader
# from src.configuration.config import datadict
newDatadict = {'BackGround': 0,
 'Bleed-Subdural': 1,
 'Scalp-Hematoma': 2,
 'Bleed-Others': 3,
 'Bleed-Intraventricular': 4,
 'Bleed-Epidural': 5,
}

class CustomDataset2D(Dataset):
    def __init__(self, image_dir, mask_dir, transform=None, datadict=newDatadict):
        self.image_dir = image_dir
        self.mask_dir = mask_dir
        self.transform = transform
        self.images = os.listdir(image_dir)
        self.series = os.listdir(mask_dir)
        self.datadict = datadict
        reversed_dict = {v: k for k, v in datadict.items()}
        self.reversed_dict = reversed_dict

    def __len__(self):
        count = 0
        for i in range(len(self.series)):
            first_folder = os.listdir(os.path.join(self.mask_dir, self.series[i]))[0]
            folder_path = os.path.join(self.mask_dir, self.series[i], first_folder)
            series_length = len(os.listdir(folder_path))
            count = count + series_length
        return count


    def transform_volume(self, image_volume, mask_volume):
        transformed = self.transform(
                image=image_volume.transpose(1, 2, 0), 
                mask=mask_volume.transpose(1, 2, 0)  # Change (9, 512, 512) -> (512, 512, 9)
            )
        images = transformed['image']
        masks = transformed['mask'].permute(2, 0, 1)
        return images , masks

        
    def __getitem__(self, index):
        count = 0
        index = index + 1
        for i in range(len(self.series)):
            first_folder = os.listdir(os.path.join(self.mask_dir, self.series[i]))[0]
            folder_path = os.path.join(self.mask_dir, self.series[i], first_folder)
            series_length = len(os.listdir(folder_path))

            if count+series_length > index:
                self.series_index = i
                index = index-count-1
                break
            elif count+series_length == index:
                self.series_index = i
                index = series_length - 1
                break
            else:
                count = count + series_length
            
        Maskvolume = []
        ImageVolume = []
        flag = 0
        for key in range(len(self.reversed_dict.keys())):
            catag = self.reversed_dict[key]
            Maskcatgvolume = []
            Masks = os.path.join(self.mask_dir, os.listdir(self.mask_dir)[self.series_index], catag)
            MasksList = os.listdir(Masks)
            MasksList = sorted(MasksList)
            
            for msk in MasksList:
                pngMask = Image.open(os.path.join(Masks, msk))
                pngMask = np.array(pngMask)
                Maskcatgvolume.append(pngMask)
        
                if msk in self.images and flag == 0:
                    pngimage = Image.open(os.path.join(self.image_dir ,msk))
                    pngimage = np.array(pngimage)
                    ImageVolume.append(pngimage)
            flag = 1
                    
            Maskcatgvolume = np.stack(Maskcatgvolume, axis = 0)
            Maskvolume.append(Maskcatgvolume)
            
        Maskvolume = np.stack(Maskvolume, axis = 0)
        ImageVolume = np.stack(ImageVolume, axis = 0)
        
        newMaskVolume = []
        for i in range(Maskvolume.shape[1]):
            newMaskVolume.append(np.argmax(Maskvolume[:,i,:,:] , axis=0))
        newMaskVolume = np.stack(newMaskVolume, axis=0)
        
        newMaskVolume[newMaskVolume>0] = -1
        newMaskVolume[newMaskVolume == 0] = 1
        newMaskVolume[newMaskVolume == -1] = 0
        
        for i in range(Maskvolume.shape[1]):
            Maskvolume[0,i,:,:] = Maskvolume[0,i,:,:] + newMaskVolume[i,:,:]


        newImageVolume = []
        newMaskVolume = []
        empty_slice = np.zeros(ImageVolume[0,:,:].shape)
        middleslice = ImageVolume[index,:,:]
        middlesliceMask = Maskvolume[:,index,:,:]
        
        if index == 0:
            if ImageVolume.shape[0] == 1:
                newImageVolume.append(empty_slice)
                newImageVolume.append(middleslice)
                newImageVolume.append(empty_slice)
                newImageVolume = np.stack(newImageVolume, axis=0)
            else:
                lastslice = ImageVolume[index+1,:,:]
                newImageVolume.append(empty_slice)
                newImageVolume.append(middleslice)
                newImageVolume.append(lastslice)
                newImageVolume = np.stack(newImageVolume, axis=0)

                
        elif index == (ImageVolume.shape[0]-1):
            firstslice = ImageVolume[index-1,:,:]
            newImageVolume.append(firstslice)
            newImageVolume.append(middleslice)
            newImageVolume.append(empty_slice)
            newImageVolume = np.stack(newImageVolume, axis=0)

        else:
            firstslice = ImageVolume[index-1,:,:]
            lastslice = ImageVolume[index+1,:,:]
            newImageVolume.append(firstslice)
            newImageVolume.append(middleslice)
            newImageVolume.append(lastslice)
            newImageVolume = np.stack(newImageVolume, axis=0)


        
        if self.transform is not None:
            transformed_image_volume, transformed_mask_volume = self.transform_volume(newImageVolume, middlesliceMask)
            

        # return image, mask
        return transformed_image_volume, transformed_mask_volume

In [55]:
from src.configuration.config import datadict

In [56]:
datadict

{'BackGround': 0,
 'Bleed-Subdural': 1,
 'Scalp-Hematoma': 2,
 'Bleed-Others': 3,
 'Bleed-Intraventricular': 4,
 'Bleed-Epidural': 5,
 'Bleed-Contusion': 6,
 'Bleed-Hematoma': 7,
 'Bleed-Subarachnoid': 8}

In [61]:
newDatadict = {
    'BackGround': 0,
    'Bleed-Subdural': 1,
    'Scalp-Hematoma': 2,
    'Bleed-Others': 3,
    'Bleed-Intraventricular': 4,
    'Bleed-Epidural': 5,
}
reversed_dict = {v: k for k, v in newDatadict.items()}

In [62]:
for key, value in reversed_dict.items():
    print(key, " ", value)

0   BackGround
1   Bleed-Subdural
2   Scalp-Hematoma
3   Bleed-Others
4   Bleed-Intraventricular
5   Bleed-Epidural


In [66]:
depth = 32
height = 512
width = 512
inputs = np.zeros((1, depth, height , width))
targets = np.zeros((1, depth, height , width))

In [67]:
inputs.shape

(1, 32, 512, 512)

In [68]:
targets.shape

(1, 32, 512, 512)

In [163]:
from torch.utils.data import Dataset, DataLoader

class BHSD_3D(Dataset):
    def __init__(self, image_dir, mask_dir, transform=None, datadict=newDatadict):
        self.image_dir = image_dir
        self.mask_dir = mask_dir
        self.transform = transform
        self.images = os.listdir(image_dir)
        self.series = os.listdir(mask_dir)
        self.datadict = datadict
        reversed_dict = {v: k for k, v in datadict.items()}
        self.reversed_dict = reversed_dict

    def transform_volume(self, image_volume, mask_volume):
        transformed = self.transform(
                image=image_volume, 
                mask=mask_volume
            )
        images = transformed['image']
        masks = transformed['mask'].permute(2, 0, 1)
        return images , masks

    

    def __len__(self):
        return len(self.images)

    def __getitem__(self, index):
        nii_segementation = nib.load(os.path.join(self.mask_dir, self.images[index]))
        nii_image = nib.load(os.path.join(self.image_dir, self.images[index]))
        
        # Get the image data as a NumPy array
        image_data = nii_image.get_fdata()
        segementation_data = nii_segementation.get_fdata()

        if self.transform is not None:
            transformed_image_volume, transformed_mask_volume = self.transform_volume(image_data, segementation_data)

        transformed_image_volume = transformed_image_volume.unsqueeze(0)
        transformed_mask_volume = transformed_mask_volume.unsqueeze(0)
        return transformed_image_volume, transformed_mask_volume

In [164]:
import albumentations as A
from albumentations.pytorch import ToTensorV2
IMAGE_HEIGHT = 256
IMAGE_WIDTH = 256
train_transform = A.Compose(
    [
        A.Resize(height=IMAGE_HEIGHT, width=IMAGE_WIDTH),
        A.Rotate(limit=35, p=1.0),
        A.HorizontalFlip(p=0.5),
        A.VerticalFlip(p=0.1),
        A.Normalize(
            mean=[0.0, 0.0, 0.0],
            std=[1.0, 1.0, 1.0],
            max_pixel_value=255.0,
        ),
        ToTensorV2(),
    ],
)


In [165]:
Dir = r"C:\Users\Rishabh\Downloads\label_192\label_192"
mask_dir = os.path.join(Dir, 'ground truths')
image_dir = os.path.join(Dir, 'images')
data = BHSD_3D(image_dir, mask_dir, transform=train_transform)

In [166]:
image_data, segementation_data = data[1]

In [167]:
image_data.shape , segementation_data.shape

(torch.Size([1, 28, 256, 256]), torch.Size([1, 28, 256, 256]))

In [171]:
import torch
def custom_collate(batch):
    max_depth = 0
    for x,y in batch:
        max_depth = max(max_depth, x.shape[1])
        # print(x.shape, ' ', y.shape)

    newImageVolume = []
    newMaskVolume = []
    for i in range(len(batch)):
        remmaining_slice = max_depth - batch[i][0].shape[1]
        # print(remmaining_slice)
        if remmaining_slice > 0:
            empty_slice = torch.zeros((1,remmaining_slice,batch[i][0].shape[2], batch[i][0].shape[3]))
            newImageVolume.append(torch.cat((batch[i][0], empty_slice), dim=1))
            newMaskVolume.append(torch.cat((batch[i][1], empty_slice), dim=1))
        else:
            newImageVolume.append(batch[i][0])
            newMaskVolume.append(batch[i][1])
    

    newImageVolume = torch.stack(newImageVolume, dim=0)
    newMaskVolume = torch.stack(newMaskVolume, dim=0)

    return newImageVolume, newMaskVolume
            
            
    # print(image_volume.shape, "  ", mask_volume.shape)
    # print("hii")

In [172]:
train_loader = DataLoader(
    data,
    batch_size=4,
    num_workers=0,
    pin_memory=True,
    shuffle=True,
    collate_fn=custom_collate
)


In [174]:
for batch_idx, (inputs, targets) in enumerate(train_loader):
    print(inputs.shape, '  ', targets.shape)

torch.Size([4, 1, 42, 256, 256])    torch.Size([4, 1, 42, 256, 256])
torch.Size([4, 1, 32, 256, 256])    torch.Size([4, 1, 32, 256, 256])
torch.Size([4, 1, 32, 256, 256])    torch.Size([4, 1, 32, 256, 256])
torch.Size([4, 1, 34, 256, 256])    torch.Size([4, 1, 34, 256, 256])
torch.Size([4, 1, 40, 256, 256])    torch.Size([4, 1, 40, 256, 256])
torch.Size([4, 1, 32, 256, 256])    torch.Size([4, 1, 32, 256, 256])
torch.Size([4, 1, 34, 256, 256])    torch.Size([4, 1, 34, 256, 256])
torch.Size([4, 1, 40, 256, 256])    torch.Size([4, 1, 40, 256, 256])
torch.Size([4, 1, 36, 256, 256])    torch.Size([4, 1, 36, 256, 256])


KeyboardInterrupt: 

In [114]:
def save_prediction(image, mask, name):
    gray_image = image
    binary_mask = mask
    
    gray_norm = gray_image / 255.0

    # Create an RGB image with grayscale as background
    overlay = np.stack([gray_norm, gray_norm, gray_norm], axis=-1)
    
    # Define lighter colors for each class (0-8)
    colors = {
        1: [1.0, 0.6, 0.6],   # Light Red
        2: [0.6, 1.0, 0.6],   # Light Green
        3: [0.6, 0.6, 1.0],   # Light Blue
        4: [1.0, 1.0, 0.6],   # Light Yellow
        5: [1.0, 0.6, 1.0],   # Light Magenta
        6: [0.6, 1.0, 1.0],   # Light Cyan
        7: [0.8, 0.7, 1.0],   # Light Purple
        8: [1.0, 0.8, 0.6]    # Light Orange
    }
    
    # Create an RGB mask initialized with zeros
    mask_rgb = np.zeros_like(overlay)

    
    # Assign colors based on binary_mask values
    for value, color in colors.items():
        mask_rgb[binary_mask == value] = color
    
    # Define transparency level
    alpha = 0.4  # Transparency level (0-1)
    
    # Blend grayscale image with the colored mask
    blended = overlay * (1 - alpha) + mask_rgb * alpha
    blended = (blended*255).astype(np.uint8)
    image = Image.fromarray(blended)
    index = len(os.listdir('Predictions'))+1
    image.save(f'Predictions/output_{name}_{index}.jpg', quality=100)

In [115]:
index = 0
for x, y in data:
    for i in range(x.shape[0]):
        image_slice = x[i,:,:]
        mask_slice = y[i,:,:]
        if len(np.unique(mask_slice)) > 1:
            save_prediction(image_slice*255, mask_slice, name = str(index))

    index =  index + 1
            
    # print(x.shape," ",y.shape)

KeyboardInterrupt: 